import { test, expect } from '@playwright/test'
import path from 'node:path'

async function signIn(page) {
  await page.goto('/')
  await page.getByLabel('Username', { exact: true }).fill('demo')
  await page.getByLabel('Password', { exact: true }).fill('synthetic-demo-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Interactive timeline' })).toBeVisible()
}

test('imported data, marker selection, exact chart/table values and date range stay consistent', async ({ page }) => {
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await signIn(page)
  await page.getByRole('button', { name: 'Clear', exact: true }).click()
  await page.getByRole('button', { name: 'Glucose Glycemic', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Glucose Glycemic', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const summary = page.locator('summary').filter({ hasText: 'Chart data' })
  await summary.click()
  const table = page.getByRole('region', { name: 'Chart data table' })
  await expect(table).toContainText('5.080')
  await expect(table).toContainText('92.00')
  await expect(table).toContainText('mg/dL')
  await expect(table).toContainText('70–110')
  await expect(page.getByRole('button', { name: /Copy Glucose, 5.080 mmol\/L/ })).toBeVisible()
  await page.getByRole('button', { name: '3M', exact: true }).click()
  await expect(table).toContainText('5.080')
  await expect(table).not.toContainText('92.00')
  await page.getByRole('button', { name: 'All time', exact: true }).click()
  await expect(table).toContainText('92.00')
  expect(errors).toEqual([])
})

test('keyboard result entry, precision, reload persistence, dialog focus and duplicate errors', async ({ page }) => {
  await signIn(page)
  const opener = page.getByRole('button', { name: 'Add result', exact: true }).first()
  await opener.focus()
  await page.keyboard.press('Enter')
  let dialog = page.getByRole('dialog', { name: 'Add a result' })
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('Marker', { exact: true }).selectOption({ label: 'TSH · mIU/L' })
  await dialog.getByLabel('Result', { exact: true }).fill('1.23400')
  await dialog.getByRole('button', { name: 'Result date', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Choose year' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Add result', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  await expect(page.getByRole('region', { name: 'Results spreadsheet' })).toContainText('1.23400')
  await opener.click()
  dialog = page.getByRole('dialog', { name: 'Add a result' })
  await dialog.getByLabel('Marker', { exact: true }).selectOption({ label: 'TSH · mIU/L' })
  await dialog.getByLabel('Result', { exact: true }).fill('2')
  await dialog.getByRole('button', { name: 'Add result', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('already exists')
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(opener).toBeFocused()
})

test('empty profiles, AI disclosure without credentials, and mobile layout', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await signIn(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const spreadsheet = page.getByRole('region', { name: 'Results spreadsheet' })
  const firstResult = spreadsheet.getByRole('button', { name: /^Edit Glucose.*5\.10 mmol\/L/ })
  const regionBox = await spreadsheet.boundingBox()
  const cellBox = await firstResult.boundingBox()
  expect(cellBox.x + cellBox.width).toBeLessThanOrEqual(regionBox.x + regionBox.width)
  await expect(firstResult.getByText('mmol/L', { exact: true })).toBeVisible()
  await firstResult.click()
  await expect(page.getByRole('dialog', { name: 'Edit result' }).getByLabel('Result', { exact: true })).toHaveValue('5.10')
  await page.keyboard.press('Escape')
  await page.getByRole('combobox', { name: 'Active profile' }).selectOption({ label: 'Empty synthetic profile' })
  await expect(page.getByText('No collection dates in this profile yet')).toBeVisible()
  await page.getByRole('combobox', { name: 'Active profile' }).selectOption({ label: 'Synthetic demo' })
  await page.getByRole('button', { name: 'Ask AI', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Optional AI analysis' })
  await expect(dialog.getByText(/No API key is included in the demo/)).toBeVisible()
  await dialog.getByRole('textbox', { name: 'Question for AI' }).fill('Summarize synthetic results')
  await expect(dialog.getByRole('button', { name: 'Send', exact: true })).toBeDisabled()
  await dialog.getByRole('checkbox').check()
  await dialog.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(dialog.getByText('Add an OpenAI API key in AI settings before using this provider.')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('capture reproducible synthetic portfolio screenshots', async ({ page }) => {
  test.skip(!process.env.UPDATE_DEMO_SCREENSHOTS, 'Screenshots are regenerated explicitly after review.')
  await signIn(page)
  await page.getByRole('button', { name: 'Clear', exact: true }).click()
  await page.getByRole('button', { name: 'Glucose Glycemic', exact: true }).click()
  await page.getByRole('button', { name: 'LDL cholesterol Lipids', exact: true }).click()
  await page.getByRole('button', { name: 'ALT Liver', exact: true }).click()
  await page.screenshot({ path: path.resolve('docs/images/synthetic-demo.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: path.resolve('docs/images/synthetic-mobile.png'), fullPage: true })
})
